### ISSUE TITLE
Switch to dxml as XML library

### ISSUE THREAD

**Issue by ghost91-** [fsimphy/bayernfahrplan#24]
## Summary

We should switch to [dxml](https://code.dlang.org/packages/dxml) for parsing XML.

## User story
As a developer, I want to use dxml for parsing XML so that I have a future proof XML solution.

## Rationale
kxml has not been updated in a loooong time it it is not possible to compile it with newer version of DMD (see https://github.com/fsimphy/bayernfahrplan/issues/21). dxml on the other hand is under active development by a well know member of the D community and according to him, he will even aim for inclusion into phobos.

## Acceptance criteria
- Remove all usages of  kxml
- Use the DOM parser of dxml for parsing  XML

**Comment by pheerai** [comment]
Closed by #25
